"""--reply: assembles a neutral, data-forward summary suitable for pasting
into a GitHub issue / HN / Reddit thread answering "is this repo legit?".

Tone rules (never violated): neutral, evidence-first, zero sales language,
never accusatory ("anomalous pattern", never "fraud"/"fake"). That
discipline already lives in each scoring module's evidence strings; this
module only assembles and labels what's already there — it does not
generate new claims.

M2.5: S1/S2/S3 evidence is now generated in whichever language the caller
requested (`compute_s1/s2/s3(..., lang=...)`), so this module's English and
Chinese renderers are both fully native today — no more mixed-language
evidence embedded in the English reply (see scoring.py's module docstring
for how that's done: co-located en/zh strings at every construction site).

S4 (AI-slop hints, v0) is excluded from `--reply` by default — it's the
highest false-positive-risk signal in the tool and doesn't belong in a
public post unless explicitly requested via `include_s4=True`
(`--include-s4` on the CLI). S4 has no score/pattern (hints only), so it
gets its own rendering block, not folded into the evidence-bullet ranking.
"""

from typing import Any

_SIGNAL_ORDER = ("s2", "s1", "s3")

_LABELS_EN = {
    "s2": "Zombie maintenance (S2)",
    "s1": "Anomalous star pattern (S1)",
    "s3": "Hallucinated dependency (S3)",
}
_LABELS_ZH = {
    "s2": "殭屍維護訊號 (S2)",
    "s1": "異常 star 模式 (S1)",
    "s3": "幻覺依賴訊號 (S3)",
}

_METHOD_NOTE_EN = (
    "Method: fixed-formula scoring, thresholds set before any repo was scored "
    "(no post-hoc tuning per target). Known limits: S1 can miss older star "
    "campaigns (it only sees an account's current state, not its state at "
    "the time it starred); S3's typosquat check compares against a curated "
    "~60-name allowlist, not a live top-N feed. Full methodology in the "
    "tool's README."
)
_METHOD_NOTE_ZH = (
    "方法：公式與門檻在查驗任何 repo 前即已定死，不對個案事後調參。已知限制："
    "S1 只看帳號目前狀態，可能漏掉較舊的 star 造假活動；S3 的 typosquat 比對"
    "只用一份約 60 個套件的人工清單，非即時 top-N 名單。完整方法見工具 README。"
)

_SIGNATURE_EN = (
    "— generated by repovet, a code-not-vibes repo trust check. A data point, not a verdict."
)
_SIGNATURE_ZH = (
    "— 由 repovet 產出（用程式碼驗證、不用感覺判斷的 repo 信任體檢工具）。"
    "這是一個資料點，不是判決。"
)

_S4_HEADER_EN = "AI-slop hints (S4, v0, experimental -- observations only, not a verdict):"
_S4_HEADER_ZH = "AI-slop 特徵提示（S4，v0，實驗性——僅為觀察，非判決）："


def _evidence_candidates(signals: dict[str, Any]) -> list[tuple[int, str, dict]]:
    candidates = []
    for key in _SIGNAL_ORDER:
        block = signals.get(key)
        if not block or block.get("status") != "ok":
            continue
        for sub in block["sub_scores"]:
            candidates.append((sub["score"], key, sub))
    return candidates


def _pick_evidence(
    signals: dict[str, Any], min_items: int = 3, max_items: int = 5
) -> list[tuple[str, dict]]:
    """Lowest-scoring sub-scores first (the most decision-relevant findings,
    whether that's a red flag or a reassuring "nothing wrong here" data
    point), across whichever signals actually ran."""
    candidates = sorted(_evidence_candidates(signals), key=lambda c: c[0])
    count = max(min(min_items, len(candidates)), min(max_items, len(candidates)))
    chosen = candidates[:count]
    return [(key, sub) for _, key, sub in chosen]


def _formula_versions(signals: dict[str, Any]) -> list[str]:
    return [
        signals[key]["formula_version"]
        for key in _SIGNAL_ORDER
        if signals.get(key) and signals[key].get("status") == "ok"
    ]


def _signal_lines(signals: dict[str, Any], labels: dict[str, str], skipped_word: str) -> list[str]:
    lines = []
    for key in _SIGNAL_ORDER:
        block = signals.get(key)
        if not block:
            continue
        label = labels[key]
        if block["status"] == "ok":
            lines.append(f"- {label}: {block['overall']}/100 ({block['pattern']})")
        elif block["status"] == "skipped":
            lines.append(f"- {label}: {skipped_word} ({block['message']})")
        else:
            lines.append(f"- {label}: {block['status']} — {block['message']}")
    return lines


def _s4_lines(signals: dict[str, Any], header: str) -> list[str]:
    block = signals.get("s4")
    if not block or block.get("status") != "ok":
        return []
    lines = ["", header]
    for hint in block["hints"]:
        lines.append(f"- {hint['name']}: {hint['observation']}")
        lines.append(f"  ({hint['disclaimer']})")
    return lines


def render_reply_en(record: dict[str, Any], include_s4: bool = False) -> str:
    signals = record["signals"]
    lines = [f"**repovet trust check — {record['target']}**", ""]
    lines.extend(_signal_lines(signals, _LABELS_EN, "skipped"))
    lines.append("")
    lines.append("Key evidence:")
    for key, sub in _pick_evidence(signals):
        lines.append(f"- [{key.upper()}] {sub['name']} ({sub['score']}/100): {sub['evidence']}")
    if include_s4:
        lines.extend(_s4_lines(signals, _S4_HEADER_EN))
    lines.append("")
    versions = ", ".join(_formula_versions(signals)) or "n/a"
    lines.append(f"Formula versions: {versions}.")
    lines.append(_METHOD_NOTE_EN)
    lines.append("")
    lines.append(_SIGNATURE_EN)
    return "\n".join(lines)


def render_reply_zh(record: dict[str, Any], include_s4: bool = False) -> str:
    signals = record["signals"]
    lines = [f"**repovet 信任體檢 — {record['target']}**", ""]
    lines.extend(_signal_lines(signals, _LABELS_ZH, "略過"))
    lines.append("")
    lines.append("關鍵證據：")
    for key, sub in _pick_evidence(signals):
        lines.append(f"- [{key.upper()}] {sub['name']}（{sub['score']}/100）：{sub['evidence']}")
    if include_s4:
        lines.extend(_s4_lines(signals, _S4_HEADER_ZH))
    lines.append("")
    versions = ", ".join(_formula_versions(signals)) or "n/a"
    lines.append(f"公式版本：{versions}。")
    lines.append(_METHOD_NOTE_ZH)
    lines.append("")
    lines.append(_SIGNATURE_ZH)
    return "\n".join(lines)


def render_reply(record: dict[str, Any], lang: str = "en", include_s4: bool = False) -> str:
    if lang == "zh":
        return render_reply_zh(record, include_s4)
    return render_reply_en(record, include_s4)
